[package]
name = "eigentrust_near"
version = "0.1.0"
edition = "2021"

[dependencies]
near-sdk = "4.0.0-pre.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.0"
csv = "1.1"

[dev-dependencies]
workspaces = "0.7.0"

[lib]
crate-type = ["cdylib"]
